---
app: sidekiq-rails-postgres-redis
tracking_branch: foo
auto_deploy: true
context: release-customer-us-west-2
domain: sidekiq-rails-postgres-redis.rls.sh.sh
mode: development
repo_name: elanderholm/sidekiq_rails_postgres_redis
hostnames:
- sidekiq: siedkiq-${env_id}-${domain}
environment_templates:
- name: ephemeral
- name: permanent
resources:
  cpu:
    limits: 1000m
    requests: 100m
  memory:
    limits: 1200Mi
    requests: 120Mi
  replicas: 1
services:
- name: sidekiq
  image: elanderholm/rails_postgres_redis/api
  has_repo: true
  args:
  - bundle
  - exec
  - sidekiq
  depends_on:
  - api
  - redis
  - db
workflows:
- name: setup
  parallelize:
  - step: mystuff
    tasks:
    - services.sidekiq
- name: patch
  parallelize:
  - step: mystuff
    tasks:
    - services.sidekiq

